title: "[General] "
labels: ["General Introduction"]
body:
  - type: textarea
    id: question
    attributes:
      label: My Question
      description: "Ask your questions here"
      value: 
    validations:
      required: true
  - type: textarea
    id: what-i-tried
    attributes:
      label: What I tried?
      description: "What solutions have I tried and what happened?"
      value: 
    validations:
      required: true