labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: My Question
      description: "Ask your questions here"
      value: 
    validations:
      required: true
  - type: markdown
    attributes:
      value: "---"  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce?
      description: "How do I recreate the problem"
      value: 
    validations:
      required: true 
  - type: markdown
    attributes:
      value: "---"    
  - type: textarea
    id: what-i-tried
    attributes:
      label: What I tried?
      description: "What solutions have I tried and what happened"
      value: 
    validations:
      required: true