title: ""
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: My Question
      description: "Explain what went wrong / what you would like to ask"
      placeholder: "Ask your questions"
      render: bash
    validations:
      required: true
  - type: textarea
    id: what-i-tried
    attributes:
      label: What have I tried?
      description: Explain what solutions have you tried yourself, and what happened
    validations:
      required: true